general:
  label: 基础设置
  items:
    customTitle:
      name: customTitle
      label: '自定义头部站点标题'
      type: text
      placeholder: '仅在页面头部标题位置显示，和Typecho后台设置的站点名称不冲突，留空则显示默认站点名称'
    PjaxOption:
      name: PjaxOption
      label: 全站Pjax
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    SidebarFixed:
      name: SidebarFixed
      label: 动态显示侧边栏
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
style:
  label: 样式设置
  items:
    HeadFixed:
      name: HeadFixed
      label: 浮动显示头部
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
others:
  label: 其他设置
  items:
    LicenseInfo:
      name: LicenseInfo
      label: '文章许可信息'
      type: text
      placeholder: '填入后将在文章底部显示你填入的许可信息（支持HTML标签），留空则默认为 (CC BY-SA 4.0)国际许可协议。'
    WeChat:
      name: WeChat
      label: '微信打赏二维码（建议图片尺寸不低于240*240）'
      type: text
      placeholder: '在这里填入一个图片 URL 地址, 以添加一个微信打赏二维码，留空则不设置微信打赏'
    Alipay:
      name: Alipay
      label: '支付宝打赏二维码（建议图片尺寸不低于240*240）'
      type: text
      placeholder: '在这里填入一个图片 URL 地址, 以添加一个支付宝打赏二维码，留空则不设置支付宝打赏'
