general:
  label: 基础设置
  items:
    customTitle:
      name: customTitle
      label: '自定义头部站点标题'
      type: text
      placeholder: '仅在页面头部标题位置显示，和Typecho后台设置的站点名称不冲突，留空则显示默认站点名称'
    PjaxOption:
      name: PjaxOption
      label: 全站Pjax
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    SidebarFixed:
      name: SidebarFixed
      label: 动态显示侧边栏
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    scrollTop:
      name: scrollTop
      label: 返回顶部
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    AjaxLoad:
      name: AjaxLoad
      label: Ajax翻页
      type: radio
      data-type: string
      default: '0'
      options:
        - value: 'auto'
          label: 自动
        - value: 'click'
          label: 点击
        - value: '0'
          label: 关闭
style:
  label: 样式设置
  items:
    HeadFixed:
      name: HeadFixed
      label: 浮动显示头部
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    InsideLinksIcon:
      name: InsideLinksIcon
      label: 友情链接显示链接图标（内页）
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
sidebar:
  label: 侧边栏
  items:
    ShowWhisper:
      name: ShowWhisper
      label: 显示最新的“日志”
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    ShowLinks:
      name: ShowLinks
      label: 首页显示链接
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    ShowHotPosts:
      name: ShowHotPosts
      label: 显示热门文章（根据访问数量排序）
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    ShowRecentPosts:
      name: ShowRecentPosts
      label: 显示最新文章
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    ShowRecentComments:
      name: ShowRecentComments
      label: 显示最近回复
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    ShowCategory:
      name: ShowCategory
      label: 显示分类
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    ShowTag:
      name: ShowTag
      label: 显示标签
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    ShowArchive:
      name: ShowArchive
      label: 显示归档
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    ShowOther:
      name: ShowOther
      label: 显示其它杂项
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
others:
  label: 其他设置
  items:
    LicenseInfo:
      name: LicenseInfo
      label: '文章许可信息'
      type: text
      placeholder: '填入后将在文章底部显示你填入的许可信息（支持HTML标签），留空则默认为 (CC BY-SA 4.0)国际许可协议。'
    WeChat:
      name: WeChat
      label: '微信打赏二维码（建议图片尺寸不低于240*240）'
      type: text
      placeholder: '在这里填入一个图片 URL 地址, 以添加一个微信打赏二维码，留空则不设置微信打赏'
    Alipay:
      name: Alipay
      label: '支付宝打赏二维码（建议图片尺寸不低于240*240）'
      type: text
      placeholder: '在这里填入一个图片 URL 地址, 以添加一个支付宝打赏二维码，留空则不设置支付宝打赏'
    MusicSet:
      name: MusicSet
      label: 背景音乐
      type: radio
      data-type: string
      default: '0'
      options:
        - value: 'order'
          label: '顺序播放'
        - value: 'shuffle'
          label: '随机播放'
        - value: '0'
          label: '关闭'
    MusicUrl:
      name: MusicUrl
      label: '背景音乐地址（建议使用mp3格式）'
      type: textarea
      placeholder: '请输入完整的音频文件路径，例如：https://music.163.com/song/media/outer/url?id={MusicID}.mp3（好东西^_-）,可设置多个音频，换行即可，一行一个，留空则关闭背景音乐'
    MusicVol:
      name: MusicVol
      label: '背景音乐播放音量（输入范围：0~1）'
      type: text
      default: '1'
      placeholder: '请输入一个0到1之间的小数（0为静音  0.5为50%音量  1为100%最大音量）输入错误内容或留空则使用默认音量100%'